org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
tokenMonitorVersionCode=630001
tokenMonitorVersionName=v0.63.0
tokenMonitorUpstreamVersion=0.63.0
tokenMonitorUpstreamTag=v0.63.0
tokenMonitorUpstreamCommit=f756d1d0fdbf415c1cd4a7178f3fe5d7a026fc90
