package io.github.theminionooo.tokenmonitor.localization

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext
import io.github.theminionooo.tokenmonitor.R
import java.util.Locale

private val labels = mapOf(
    "icon size" to R.string.ui_cf4_a86cafc756,
    "home units" to R.string.ui_cf4_473d53e5a8,
    "on uses 万/亿; off uses k/m/b. applies only to home token values." to R.string.ui_cf4_28123b8b80,
    "changes content icons independently of text size. navigation and widgets keep their sizes." to R.string.ui_cf4_324e02b3f6,
    "abbreviate the home total using the selected home units." to R.string.ui_cf4_f4e818d28b,
    "home" to R.string.ui_e83249bd3ba7,
    "tools" to R.string.ui_0284c6ac58cb,
    "models" to R.string.ui_5ba2688dffd7,
    "devices" to R.string.ui_728190e74db3,
    "projects" to R.string.ui_b37b5674e3d0,
    "sessions" to R.string.ui_781791f54cc0,
    "limits" to R.string.ui_9523ccbcc4c5,
    "trends" to R.string.ui_f433de78feab,
    "status" to R.string.ui_48a3661d8464,
    "settings" to R.string.ui_3cc1d5a427a4,
    "day" to R.string.ui_a2620cbc10f5,
    "today" to R.string.ui_2dd2bed72567,
    "month" to R.string.ui_021710fa7866,
    "total" to R.string.ui_5a537e209151,
    "week" to R.string.ui_c0ee32d825d6,
    "this week" to R.string.ui_dae1e5f83a74,
    "this month" to R.string.ui_0bd41b476166,
    "last 7 days" to R.string.ui_7252f9e8d5bd,
    "last 30 days" to R.string.ui_6a725a2b98e1,
    "7 days" to R.string.ui_0a8dd6adce7a,
    "30 days" to R.string.ui_7d4278a87590,
    "90 days" to R.string.ui_170621ac0842,
    "1 year" to R.string.ui_afe36da67645,
    "all" to R.string.ui_d87c448044de,
    "all usage" to R.string.ui_2b63a9f923a1,
    "language" to R.string.ui_e11523c5ff23,
    "follow system" to R.string.ui_0dbaa1fce242,
    "simplified chinese" to R.string.ui_36a0d9fbd092,
    "english" to R.string.ui_1b669334dae8,
    "connection" to R.string.ui_814605c64a5c,
    "home wi-fi" to R.string.ui_17d3aee24c19,
    "home fallback" to R.string.ui_ba90df5372a1,
    "check and save connection" to R.string.ui_f893ea0e3c0c,
    "disconnect this phone" to R.string.ui_d5c99c52d020,
    "pair with desktop" to R.string.ui_abf63a5a0753,
    "3 steps" to R.string.ui_e5516ba492f0,
    "appearance" to R.string.ui_85a7b4e8d512,
    "interface theme" to R.string.ui_a37043098817,
    "default" to R.string.ui_7505d64a54e0,
    "obsidian" to R.string.ui_94517207d686,
    "porcelain" to R.string.ui_a0ffe732ea1c,
    "theme code" to R.string.ui_f7b69b7c1dff,
    "that is not a tm1 theme code." to R.string.ui_e88fbb5bf63f,
    "paste a code from the desktop's appearance settings to use the same colors here." to R.string.ui_e8a2309148c9,
    "apply" to R.string.ui_69f45da1683c,
    "follow phone light and dark" to R.string.ui_4525db4a29e8,
    "follows phone" to R.string.ui_1c20cf1d0a88,
    "live indicator" to R.string.ui_bf8c91a9d5f9,
    "show the small dot beside the σ while the stream is live." to R.string.ui_35bd11a81363,
    "tool icons" to R.string.ui_59963d94cfaa,
    "show provider marks beside tools and models instead of plain dots." to R.string.ui_572547c085b3,
    "colorful tool marks" to R.string.ui_9ae0d24bc2af,
    "use original provider colors instead of monochrome marks." to R.string.ui_773fd1972ce8,
    "compact token total" to R.string.ui_e7ffaedcf4cd,
    "use abbreviated totals such as 214.9m in the main header." to R.string.ui_f3672df0ea8c,
    "text size" to R.string.ui_1119b42f81f7,
    "compact" to R.string.ui_4f44e2cffa8f,
    "comfortable" to R.string.ui_2b867d9270e0,
    "large" to R.string.ui_5296d5cced2a,
    "compact matches the desktop widget exactly. comfortable and large enlarge every label for reading at arm's length." to R.string.ui_81b56b1c62bb,
    "reduce motion" to R.string.ui_6b44cd1f85be,
    "system" to R.string.ui_317f1e761f2f,
    "on" to R.string.ui_db3d405b1067,
    "off" to R.string.ui_da7a68734367,
    "system follows android. on minimizes motion; off keeps the app's interaction animations." to R.string.ui_a92daaa954ee,
    "main dashboard" to R.string.ui_ca21d9bd8373,
    "default usage range" to R.string.ui_227a3ca00535,
    "views" to R.string.ui_81f331871472,
    "home modules" to R.string.ui_e2d08459faf5,
    "usage presentation" to R.string.ui_4bc2ab234d33,
    "model and tool ranking" to R.string.ui_eaa35cb863f7,
    "tokens" to R.string.ui_3391436a4e72,
    "cost" to R.string.ui_885dc4a9b362,
    "show limit source" to R.string.ui_2b83391b81f4,
    "display which hub device supplied each provider limit." to R.string.ui_f0b876d989d6,
    "show account emails" to R.string.ui_f719f49b6df2,
    "useful only when provider names are not enough to distinguish accounts." to R.string.ui_47510716c745,
    "show session titles" to R.string.ui_aca1e2c1a73e,
    "hide reported titles in home and sessions. this display choice does not remove titles from the local snapshot cache." to R.string.ui_e81daa6a4f48,
    "limit bars show" to R.string.ui_b572d06086fe,
    "remaining" to R.string.ui_398658a601d9,
    "used" to R.string.ui_192a56759d36,
    "stream live" to R.string.ui_2c189c3d81cb,
    "widget live" to R.string.ui_3e20a037533f,
    "snapshot" to R.string.ui_e94025be336b,
    "hub status" to R.string.ui_a34add9c2858,
    "route" to R.string.ui_fc166eb81361,
    "hub build" to R.string.ui_3a06c1584e8e,
    "runtime" to R.string.ui_f2e18ffc17e2,
    "not reported" to R.string.ui_4b71ecf8c893,
    "collector role" to R.string.ui_489ad9525abc,
    "last read" to R.string.ui_eb7bf9cc53c8,
    "unknown" to R.string.ui_50d8b4a941c2,
    "phone data" to R.string.ui_9991907ae002,
    "saved snapshot" to R.string.ui_c1fe37dce01e,
    "current" to R.string.ui_405ab5d2b930,
    "home-screen widget" to R.string.ui_96e01ce53b98,
    "live controls · resizable" to R.string.ui_97c3ff340ea3,
    "a widget in your app theme with the full token count, tool marks, quota windows, and a seven-day chart as you make it taller. reduce motion also applies to the widget." to R.string.ui_3538e067b3a1,
    "tap refresh for one update, or live for 60-second hub updates for up to an hour while the app is closed. tap live again or stop in the notification to finish. android may delay updates while the phone sleeps. figures and the last update time are visible on your home screen." to R.string.ui_33f2009999b3,
    "add widget" to R.string.ui_2dd2304b135c,
    "long-press your home screen, choose widgets, then token monitor." to R.string.ui_a45dec2e4aa8,
    "compatibility" to R.string.ui_4547bd227f90,
    "android app" to R.string.ui_f997b36b1b15,
    "desktop baseline" to R.string.ui_da5aa24b34d5,
    "protocol changes are reviewed against versioned fixtures before this baseline moves forward." to R.string.ui_c8e0daf9debd,
    "app updates" to R.string.ui_93f285223942,
    "the dashboard streams immediately while visible. widget live uses a lighter 60-second refresh and stops after one hour." to R.string.ui_475b43e19d3b,
    "hub address" to R.string.ui_fe21a32fbf54,
    "cloudflare: paste the complete https base address, without /api/stats. https defaults to port 443. bare tailscale or lan addresses use http port 17321." to R.string.ui_222cbc2f0c92,
    "home wi-fi address (optional)" to R.string.ui_9d32b680780a,
    "private desktop hub only. use this only if it shares the same data and secret as the primary hub; otherwise leave it blank." to R.string.ui_3703287c6c15,
    "find" to R.string.ui_ded8dae5786f,
    "hub secret" to R.string.ui_c9ed699f13e9,
    "stored with an android keystore key and never shown after saving." to R.string.ui_3986698135c7,
    "allow a private wi-fi hub" to R.string.ui_5fc913876cc5,
    "enable only for a 10.x, 172.16–31.x, 192.168.x, or .local hub. public https hubs do not require this switch." to R.string.ui_662c8c79872a,
    "checking hub…" to R.string.ui_e2ffb6aa78b5,
    "your desktop dashboard, live on your phone." to R.string.ui_d4911489c222,
    "connect your hub" to R.string.ui_00d3c7ab5e0e,
    "choose your existing hub" to R.string.ui_cc2a08ca0550,
    "use your cloudflare https hub, or a desktop hub over tailscale or home wi-fi." to R.string.ui_7a1672916de4,
    "enter its base address" to R.string.ui_8778f2819b3c,
    "cloudflare uses https://your-hub.example.com. for a desktop hub, use its private address and port." to R.string.ui_9b424030a94b,
    "enter the shared hub secret" to R.string.ui_48612ee2988e,
    "use the token monitor hub secret, not a cloudflare account api token. check and save to connect." to R.string.ui_4905ecd1397f,
    "connect" to R.string.ui_f11a107f3832,
    "usage is read from the hub you configure. credentials are encrypted with android keystore. this independent cloudflare edition uses manually installed updates." to R.string.ui_d40ebebf5bad,
    "this phone only reads your token monitor hub. https cloudflare hubs and private desktop hubs are supported." to R.string.ui_ef542ec29ddb,
    "the saved hub is shown below. enter the secret again only to change the connection." to R.string.ui_ed40bdf3fce2,
    "1. install tailscale on the desktop and phone, then use the same tailnet." to R.string.ui_6bb963c298a3,
    "2. in the desktop app, open settings → multi-device sync and choose host hub." to R.string.ui_6961a573f74f,
    "3. type the address that starts with 100. and the shared secret from the desktop app into the fields above. just the numbers are enough." to R.string.ui_de9d4a2bd490,
    "always" to R.string.ui_6656018ac96d,
    "installed" to R.string.ui_85841abddb12,
    "edition" to R.string.ui_194562b97b02,
    "cloudflare compatible" to R.string.ui_40d57ec40577,
    "this independent edition uses a separate package and signing key. automatic upstream update checks and apk installation are disabled. install future updates supplied for this edition; upstream apks do not update it." to R.string.ui_e69243169611,
    "refresh" to R.string.ui_26b56c1bdfb0,
    "refreshing" to R.string.ui_6e9c6c40ef0a,
    "hub connection" to R.string.ui_566922711684,
    "choose view" to R.string.ui_ba99bb93eac1,
    "back to home" to R.string.ui_22b9d367d228,
    "open connection settings" to R.string.ui_1a65187c1435,
    "connect a private hub to see desktop activity here." to R.string.ui_9855d66264dd,
    "total tokens" to R.string.ui_37b0b298d34e,
    "total cost" to R.string.ui_b62e84ef991c,
    "active days" to R.string.ui_a95412829684,
    "current streak" to R.string.ui_37e4cf575dec,
    "active time" to R.string.ui_58aeec48ee89,
    "peak day" to R.string.ui_76273bde2ee8,
    "top model" to R.string.ui_0c9ab00119ad,
    "messages" to R.string.ui_17f3467db103,
    "token activity" to R.string.ui_8c9a3662c1d6,
    "monthly history" to R.string.ui_de7f325675fa,
    "overview" to R.string.ui_fed758b7a842,
    "by model · available history" to R.string.ui_df57214a3f23,
    "by tool · available history" to R.string.ui_d6236d66cbb8,
    "by tool" to R.string.ui_9346e6873489,
    "by model" to R.string.ui_40b3e4787894,
    "bars" to R.string.ui_5a599b482fc1,
    "k-line" to R.string.ui_55a5b53ace4b,
    "no daily history is available yet." to R.string.ui_20cb6548b2cd,
    "no quota windows were reported." to R.string.ui_532ff263f570,
    "no low quota or imminent reset in the reported windows." to R.string.ui_b4160c93ea40,
    "quota is provider-reported. usage costs are estimates; subscriptions are recorded payments." to R.string.ui_109d75e96a89,
    "quota at a glance" to R.string.ui_f54cea9c34fc,
    "no account limits available" to R.string.ui_782f8d94f45c,
    "provider" to R.string.ui_90c5d1358d12,
    "no quota windows reported" to R.string.ui_9970e38fb5b8,
    "no activity for this period" to R.string.ui_08d5a41b5b7f,
    "no devices have checked in" to R.string.ui_d27ac317998e,
    "stale" to R.string.ui_a4e976a3d3fc,
    "synced" to R.string.ui_53e7f55a8d1b,
    "trend" to R.string.ui_48075864b259,
    "no recent sessions reported by the hub" to R.string.ui_b21966e3375a,
    "input (cache hit)" to R.string.ui_5ae59fb6202a,
    "input (cache miss)" to R.string.ui_93ee0e5ec73e,
    "output" to R.string.ui_1029d6764481,
    "unclassified" to R.string.ui_34f307fe88d3,
    "the hub reports projects for day, month, and total only." to R.string.ui_a183f379b56e,
    "project total" to R.string.ui_adea0a239e3a,
    "the hub reports sessions for day, month, and total only." to R.string.ui_d3867c9fd275,
    "running" to R.string.ui_3c49d9cc3c0c,
    "finished" to R.string.ui_f957097d7a22,
    "collapse session details" to R.string.ui_0832cf38702e,
    "expand session details" to R.string.ui_97e3a2bd2855,
    "project" to R.string.ui_98f54143ab4e,
    "started" to R.string.ui_da7153ee73f1,
    "session" to R.string.ui_fcbdc4c271c8,
    "checking claude, openai, cursor, and deepseek…" to R.string.ui_267de1f808a2,
    "operational" to R.string.ui_7a65affc3de3,
    "degraded" to R.string.ui_6dc244693635,
    "outage" to R.string.ui_fa74c4abe6b7,
    "no ongoing issues" to R.string.ui_567b6277bc84,
    "no account limits are available from this hub yet." to R.string.ui_b48685e3efdb,
    "subscriptions" to R.string.ui_9bbb0db0d9f4,
    "not signed in" to R.string.ui_9ad3d4009682,
    "sign in again" to R.string.ui_6ce9faa8a460,
    "disabled" to R.string.ui_07596f183f5e,
    "no synced data" to R.string.ui_82fd15b8052f,
    "limited" to R.string.ui_1eb7d5c2200d,
    "unavailable" to R.string.ui_1d5ee313d50a,
    "no quota reported" to R.string.ui_bf8d1489e7d5,
    "not available" to R.string.ui_5f2391220833,
    "available" to R.string.ui_7b231a50a498,
    "subscription" to R.string.ui_dc917a775356,
    "period comparison" to R.string.ui_06e7a6229940,
    "model changes use reported attribution; missing breakdowns are not estimated." to R.string.ui_b3187554708b,
    "explore usage" to R.string.ui_0614aad07beb,
    "tap a tool or model to see its recorded daily usage." to R.string.ui_825a1224c0b2,
    "find a tool or model" to R.string.ui_5b0cac7364e4,
    "no matching attribution in the available history." to R.string.ui_5d875efb1bcb,
    "no observation was supplied for this date." to R.string.ui_3ee79499a845,
    "the hub has no breakdown for this day." to R.string.ui_c3b31971ad84,
    "sessions and projects are available for the hub's day, month, and total periods." to R.string.ui_5f0df686bfb9,
    "daily usage, newest first. costs are estimates from the desktop hub." to R.string.ui_1b54373af2bb,
    "close" to R.string.ui_da38860cb875,
    "search tool, model, or project" to R.string.ui_957ce7cc917e,
    "all models" to R.string.ui_c9d163f8d33b,
    "usage through this tool in the selected period" to R.string.ui_9f998fbfb5f2,
    "← back to tools" to R.string.ui_6398a16d8178,
    "no tool activity is available for this period." to R.string.ui_f02b083758c4,
    "no tool-to-model breakdown was supplied for this period." to R.string.ui_c6ffaea84550,
    "no model activity is available for this period." to R.string.ui_7d452f90f9f1,
    "activity heatmap. open daily details or use the day navigation below." to R.string.ui_3394262f6c32,
    "open latest recorded day" to R.string.ui_af9bb0c4e962,
    "no recorded usage" to R.string.ui_c5e6b67922a3,
    "previous" to R.string.ui_355f28f2c0c3,
    "details" to R.string.ui_e9711657b066,
    "next day" to R.string.ui_c3c59829ba11,
    "reset now" to R.string.ui_78b63506fb42,
    "now" to R.string.ui_c9bc849a968f,
    "just now" to R.string.ui_a7f8e7cc0d43,
    "an unknown time" to R.string.ui_e5d8e78c9348,
    "recently" to R.string.ui_fd92cc8545a9,
    "5-hour" to R.string.ui_bc42882d967c,
    "daily" to R.string.ui_2fe14b9b993e,
    "weekly" to R.string.ui_c803e4261886,
    "monthly" to R.string.ui_745d1918a44b,
    "billing" to R.string.ui_acd14c7a6c04,
    "limit" to R.string.ui_e4d68c5a97e4,
    "third-party" to R.string.ui_b27deb66bcd0,
    "third-party apis" to R.string.ui_9cc167f8df85,
    "tailscale" to R.string.ui_15f90b181664,
    "private network" to R.string.ui_c3e43e15c2b0,
    "https hub" to R.string.ui_6ac3cf070e92,
    "cloudflare hub" to R.string.ui_b1e471b0d308,
    "enter the hub secret before connecting." to R.string.ui_6a6a39ac493f,
    "the hub secret must not contain control characters or line breaks." to R.string.ui_842ff3b32076,
    "the hub address must not contain spaces or control characters." to R.string.ui_b3e43b7e2ea7,
    "enter a complete https hub address or a private desktop address." to R.string.ui_0bb59edad8e4,
    "only http and https hub urls are supported." to R.string.ui_bd34ae633d40,
    "use only a hub host and optional port; do not include credentials or a path." to R.string.ui_c176208b7680,
    "use the hub base address, without an api path." to R.string.ui_0f1c2e5ccaae,
    "use a valid hub port." to R.string.ui_5c4a5aaf3f15,
    "public hubs require a complete https:// address. enable private wi-fi only for a lan hub." to R.string.ui_4771c8471509,
    "live" to R.string.ui_98aadb37083e,
    "offline" to R.string.ui_d1ffda5dc990,
    "saved" to R.string.ui_c75c31dffb08,
    "updating" to R.string.ui_6cb858eeb95b,
    "no data" to R.string.ui_4d968a30a022,
    "account" to R.string.ui_ca20728d35f0,
    "accounts" to R.string.ui_10db2797df2c,
    "balance" to R.string.ui_8dfa30e02450,
    "device name" to R.string.ui_b121c3558238,
    "device alias" to R.string.ui_d54f14127298,
    "rename device" to R.string.ui_c62fcd7c434b,
    "save" to R.string.ui_13a4a11319d3,
    "cancel" to R.string.ui_4fd0653c4f2a,
    "restore original name" to R.string.ui_08ed90a4660b,
    "hub original name" to R.string.ui_7dfa9f2f7b2b,
    "name on this phone" to R.string.ui_fe25deae7c1b,
    "local name" to R.string.ui_6d230c03e544,
    "original name" to R.string.ui_e4a3590a3f83,
    "remove alias" to R.string.ui_7a02c2d23dbe,
    "no devices have checked in to this hub." to R.string.ui_36a1a83c01e5,
    "top models on this device" to R.string.ui_d753002d5011,
    "history available" to R.string.ui_825f208629e0,
    "live uploads" to R.string.ui_ca2389cc0ef8,
    "only saved on this phone, up to 32 characters" to R.string.ui_324f668fd2a0,
    "name on this android device" to R.string.ui_a2119851b299,
    "please connect a hub first" to R.string.ui_49c9b2ba3127,
    "connection check cancelled. try again." to R.string.ui_307915d70042,
    "connection check paused. try again." to R.string.ui_323c0b0ae60e,
    "connected securely to the hub." to R.string.ui_62bd5c856c60,
    "the saved hub connection was removed from this phone." to R.string.ui_8630ae57d0e5,
    "live updates paused. retrying..." to R.string.ui_bd8ad6ed86a0,
    "hub unavailable. showing the last successful snapshot; retrying..." to R.string.ui_37ab578b9e1d,
    "the address is not a token monitor hub." to R.string.ui_f9a8829f88e1,
    "the hub did not return valid statistics. showing the last successful snapshot." to R.string.ui_7126ec5be83c,
    "the hub did not return an event stream. using periodic updates instead." to R.string.ui_c451f1c2dea1,
    "the hub rejected the secret. check the connection settings." to R.string.ui_2eb73a3630f9,
    "this hub endpoint is not available. update the desktop token monitor hub." to R.string.ui_1f3b9cdd209d,
    "the hub stream event is too large for this phone dashboard." to R.string.ui_b20942b85704,
    "the hub stream line is too large for this phone dashboard." to R.string.ui_1d379e51fa82,
    "the hub response is too large for this phone dashboard." to R.string.ui_abba2b9bcadb,
    "could not securely save the hub connection." to R.string.ui_683563945ee4,
    "could not remove the saved hub connection." to R.string.ui_13fc449d0eef,
    "no hub answered on this wi-fi. check that the desktop app is running with host hub on, then try again." to R.string.ui_345a3c68463d,
    "no data from the hub yet." to R.string.ui_bf57b8759d1f,
    "idle" to R.string.ui_1adbcc344b31,
    "device names cannot contain line breaks or control characters." to R.string.ui_6b720ea3ddd6,
    "device names can contain at most 32 characters." to R.string.ui_c264359dbf16,
    "could not save the device name. try again." to R.string.ui_4c60bb7ad58e,
    "connect to a hub first." to R.string.ui_6b202d5adea7,
    "freshness unavailable" to R.string.ui_a31a0ff3e522,
    "saved quota; refresh to confirm" to R.string.ui_1f8a649f17d9,
    "awaiting updated quota" to R.string.ui_0a7d9eb756bc,
    "the hub could not be verified. check the https or private hub address and try again." to R.string.ui_18e916c53e35,
    "could not save language. try again." to R.string.ui_6dfea94b67dc,
)

private val templates = listOf(
    Regex("Context (.+)% left") to R.string.ui_tpl_context_left,
    Regex("Context (.+)% used") to R.string.ui_tpl_context_used,
    Regex("(.+)% left") to R.string.ui_tpl_remaining_percent,
    Regex("(.+)% used") to R.string.ui_tpl_used_percent,
    Regex("(\\d+) running") to R.string.ui_tpl_running_count,
    Regex("(\\d+) sessions") to R.string.ui_tpl_session_count,
    Regex("(\\d+) messages") to R.string.ui_tpl_message_count,
    Regex("(\\d+) active days?") to R.string.ui_tpl_active_days,
    Regex("(\\d+) days \u00b7 (.+)") to R.string.ui_tpl_day_cost,
    Regex("Cache hit (.+)%") to R.string.ui_tpl_cache_hit,
    Regex("(.+) tok/s") to R.string.ui_tpl_speed,
    Regex("Cache estimate ~(.+) min left") to R.string.ui_tpl_cache_estimate,
    Regex("Models used through (.+)") to R.string.ui_tpl_model_through,
    Regex("(.+) \u00b7 Models") to R.string.ui_tpl_tool_models,
    Regex("Updated (.+)") to R.string.ui_tpl_updated,
    Regex("Source (.+)") to R.string.ui_tpl_source,
    Regex("Peak (.+)") to R.string.ui_tpl_peak,
    Regex("Reset (.+)") to R.string.ui_tpl_reset,
    Regex("Expires (.+)") to R.string.ui_tpl_expires,
    Regex("Changes(?: in)? (.+)") to R.string.ui_tpl_changes,
    Regex("(.+) ago") to R.string.ui_tpl_age,
    Regex("(\\d+)d (\\d+)h") to R.string.ui_tpl_duration_dh,
    Regex("(\\d+)h (\\d+)m") to R.string.ui_tpl_duration_hm,
    Regex("(\\d+)m") to R.string.ui_tpl_duration_m,
    Regex("(\\d+)s") to R.string.ui_tpl_duration_s,
    Regex("<1m") to R.string.ui_tpl_duration_short,
    Regex("Open (Home|Tools|Models|Devices|Sessions|Limits|Trends|Projects|Status)") to R.string.ui_tpl_open,
    Regex("Collapse (.+)") to R.string.ui_tpl_collapse,
    Regex("Expand (.+)") to R.string.ui_tpl_expand,
    Regex("Move (.+) up") to R.string.ui_tpl_move_up,
    Regex("Move (.+) down") to R.string.ui_tpl_move_down,
    Regex("Explore (.+)") to R.string.ui_tpl_explore,
    Regex("Saved snapshot \u00b7 (.+)") to R.string.ui_tpl_snapshot_age,
    Regex("(\\d+) affected") to R.string.ui_tpl_affected,
    Regex("(\\d+) incidents?") to R.string.ui_tpl_incidents,
    Regex("(\\d+) maintenance") to R.string.ui_tpl_maintenance,
    Regex("No project attribution is available for (.+)\\.") to R.string.ui_tpl_projects_missing,
    Regex("No session detail is available for (.+)\\.") to R.string.ui_tpl_sessions_missing,
    Regex("The v(.+) desktop app does not generate a pairing QR code\\.") to R.string.ui_tpl_qr,
    Regex("Prompt and reply text stays on the desktop and is not synchronized by the v(.+) Hub\\.") to R.string.ui_tpl_prompt_local,
    Regex("Last (\\d+) completed days vs preceding (\\d+)") to R.string.ui_tpl_compare_days,
    Regex("Estimated cost: (.+) vs (.+)") to R.string.ui_tpl_compare_cost,
    Regex("(\\d+) more matches\\. Refine the search to find them\\.") to R.string.ui_tpl_more_matches,
    Regex("Incomplete history: (\\d+)/(\\d+) and (\\d+)/(\\d+) days recorded\\. Missing days are not treated as zero; percentage change is unavailable\\.") to R.string.ui_tpl_incomplete,
    Regex("(.+) tokens \u00b7 (.+) estimated") to R.string.ui_tpl_usage_estimate,
    Regex("(.+) tokens \u00b7 (.+)") to R.string.ui_tpl_usage_cost,
    Regex("(.+) tokens across (\\d+) recorded days?") to R.string.ui_tpl_recorded_days,
    Regex("(.+) vs (.+) tokens") to R.string.ui_tpl_compare_tokens,
    Regex("(.+) tokens") to R.string.ui_tpl_token_count,
    Regex("(\\d+)/(\\d+) views \u00b7 (.+)") to R.string.ui_tpl_view_summary,
    Regex("(.+); awaiting updated quota") to R.string.ui_tpl_awaiting_quota,
    Regex("Hub original name: (.+)") to R.string.ui_tpl_hub_original,
    Regex("Uploads every (.+)") to R.string.ui_tpl_uploads,
    Regex("Synced (.+)") to R.string.ui_tpl_synced_age,
    Regex("(.+) \u00b7 (Synced.*|Stale)") to R.string.ui_tpl_device_status,
    Regex("(.+) \u00b7 History available") to R.string.ui_tpl_device_history,
    Regex("Found your desktop at (.+)\\.") to R.string.ui_tpl_found,
    Regex("The Hub returned HTTP (\\d+)\\. Try again when it is online\\.") to R.string.ui_tpl_http_error,
    Regex("Home Wi-Fi address: (.+)") to R.string.ui_tpl_fallback_error,
    Regex("(Follows phone|Default|Obsidian|Porcelain) \u00b7 (Compact|Comfortable|Large)") to R.string.ui_tpl_appearance_summary,
    Regex("(Tokens|Cost) \u00b7 (Remaining|Used)") to R.string.ui_tpl_usage_summary,
    Regex("Porcelain while the phone is in light mode, (.+) at night\\. Widgets follow at their next update\\.") to R.string.ui_tpl_follow_theme,
 )

private val translatedCaptureResources = setOf(
    R.string.ui_tpl_open, R.string.ui_tpl_collapse, R.string.ui_tpl_expand,
    R.string.ui_tpl_move_up, R.string.ui_tpl_move_down, R.string.ui_tpl_reset,
    R.string.ui_tpl_expires, R.string.ui_tpl_changes, R.string.ui_tpl_age,
    R.string.ui_tpl_projects_missing, R.string.ui_tpl_sessions_missing,
    R.string.ui_tpl_view_summary, R.string.ui_tpl_uploads, R.string.ui_tpl_synced_age,
    R.string.ui_tpl_device_status, R.string.ui_tpl_device_history, R.string.ui_tpl_fallback_error,
    R.string.ui_tpl_appearance_summary, R.string.ui_tpl_usage_summary, R.string.ui_tpl_follow_theme,
)


/** Call only for app-owned labels and known message templates, never raw Hub names. */
fun uiText(context: Context, text: String): String {
    val localized = localizedContext(context)
    if (localized.resources.configuration.locales[0].language != "zh") return text
    labels[text.lowercase(Locale.ROOT)]?.let { return localized.getString(it) }
    for ((pattern, resource) in templates) {
        val match = pattern.matchEntire(text) ?: continue
        val arguments = match.groupValues.drop(1).map { value ->
            // Translate only known status, range and duration fragments. Other captures are preserved.
            if (resource in translatedCaptureResources) uiText(localized, value) else value
        }.toTypedArray()
        return localized.getString(resource, *arguments)
    }
    return text
}

@Composable fun tr(text: String): String = uiText(LocalContext.current, text)

/** Non-Compose presentation helpers keep English in JVM-only tests before app initialization. */
fun localizedText(text: String): String = LanguagePreferences.context()?.let { uiText(it, text) } ?: text
